Fix/sensitive output
claranet/terraform-azurerm-function-app pull request #7
Opened 2024-02-18 21:27 UTC by joaolms

Fixes #6.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Changes proposed in this pull request

- Add ```sensitive = true``` for linux and windows functions

@claranet/fr-azure-reviewers

2024-02-20 08:00 UTC, jmapro approved these changes
LGTM

2024-02-20 08:20 UTC, Shr3ps requested changes

2024-02-20 08:20 UTC, Shr3ps commented on outputs.tf
> +  sensitive   = true
Hum no, I fully disagree with this.
It will prevent using correctly the module and access properties in a stack context with Terraform or OpenTofu.

2024-02-20 08:22 UTC, Shr3ps commented
> LGTM

nope, I think we don't want this.
@joaolms please give more details in your opened issue, and how you got the error exactly.

2024-06-24 13:17 UTC, kayahk commented
We had the same issue with the missing `sensitive = true` argument in the `eventhub` module and now we see it here in the `function-app` module, too.
```
module.linux_function["enabled"].module.diagnostics.azurerm_monitor_diagnostic_setting.main[0]: Creation complete after 4s [id=/subscriptions/f7c1a591-6b7c-4aee-b0aa-3ef509b9218a/resourceGroups/rg-sgc-sus-ops1-germanywestcentral/providers/Microsoft.Web/sites/fun-sgc-sus-ops1-germanywestcentral|default]
╷
│ Error: Output refers to sensitive values
│ 
│   on outputs.tf line 1:
│    1: output "linux_function_app" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true
```
I can't exactly follow why adding the `sensitive` argument would prevent using the module correctly - in fact, it would make the module usable (at all) for us in the first place. It shouldn't be a problem to keep existing references to outputs, they wouldn't be impacted by changing from non-sensitive to sensitive.

2024-06-24 15:01 UTC, Shr3ps commented
> We had the same issue with the missing `sensitive = true` argument in the `eventhub` module and now we see it here in the `function-app` module, too.
> 
> ```
> module.linux_function["enabled"].module.diagnostics.azurerm_monitor_diagnostic_setting.main[0]: Creation complete after 4s [id=/subscriptions/f7c1a591-6b7c-4aee-b0aa-3ef509b9218a/resourceGroups/rg-sgc-sus-ops1-germanywestcentral/providers/Microsoft.Web/sites/fun-sgc-sus-ops1-germanywestcentral|default]
> ╷
> │ Error: Output refers to sensitive values
> │ 
> │   on outputs.tf line 1:
> │    1: output "linux_function_app" {
> │ 
> │ To reduce the risk of accidentally exporting sensitive data that was
> │ intended to be only internal, Terraform requires that any root module
> │ output containing sensitive data be explicitly marked as sensitive, to
> │ confirm your intent.
> │ 
> │ If you do intend to export this data, annotate the output value as
> │ sensitive by adding the following argument:
> │     sensitive = true
> ```
> 
> I can't exactly follow why adding the `sensitive` argument would prevent using the module correctly - in fact, it would make the module usable (at all) for us in the first place. It shouldn't be a problem to keep existing references to outputs, they wouldn't be impacted by changing from non-sensitive to sensitive.

Adding `sensitive` to a complete resource outputted (which is not a "simple" value), of type of map/object is against Terraform best practices, it will prevent to be able to easily use outputs attributes from one module to another directly, it will requires the usage of `nonsensitive` on many output calls.

If you read again your error message, it seems that with Terragrunt and in your context this repository **is not used as a module** like it should be in the Terraform/OpenTofu ecosystem. It seems the repo is used as a "root module" (also called a Terraform Stack: https://www.hashicorp.com/blog/terraform-stacks-explained) but it should not.

So to be able to correctly use this module, like many others (for example official Azure one: https://github.com/Azure/terraform-azurerm-avm-res-eventhub-namespace/blob/main/outputs.tf) you should consider using the standard Terraform/OpenTofu way to call modules.

2024-06-24 15:01 UTC, closed without merging

2024-06-24 15:43 UTC, kayahk commented
@Shr3ps thanks for your comment, I understand your position regarding the opinionated approach following Terraform (or OpenTofu). Unfortunately, a stack in Terragrunt can indeed be a collection of modules - regardless if root or not - since Terragrunt itself acts as the wrapping orchestrator instead of the `stack` concept propagated by Hashicorp. We don't have any issues with referencing output attributes across the entire stack, while it is true that the references can be somewhat easier to lookup with non-sensitive primitive types.
Bottom line is that we have to look for another way to implement the modules in question, that's all.